{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n",
      "/usr/local/lib/python3.6/dist-packages/apache_beam/__init__.py:84: UserWarning: Running the Apache Beam SDK on Python 3 is not yet fully supported. You may encounter buggy behavior or missing features.\n",
      "  'Running the Apache Beam SDK on Python 3 is not yet fully supported. '\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import sys\n",
    "import h5py\n",
    "import argparse\n",
    "import numpy as np\n",
    "from collections import Counter\n",
    "import xml.etree.ElementTree as et \n",
    "\n",
    "# Keras imports\n",
    "from keras.models import Model\n",
    "from keras.optimizers import Adam\n",
    "from keras.utils.vis_utils import model_to_dot\n",
    "from keras.layers import Input, Dense, Dropout, AlphaDropout, BatchNormalization, Activation\n",
    "\n",
    "import matplotlib\n",
    "matplotlib.use('Agg') # Need this to write images from the GSA servers.  Order matters:\n",
    "import matplotlib.pyplot as plt # First import matplotlib, then use Agg, then import plt\n",
    "\n",
    "# IPython imports\n",
    "from IPython.display import Image\n",
    "\n",
    "# ML4CVD Imports\n",
    "from ml4cvd.arguments import parse_args\n",
    "from ml4cvd.tensor_writer_ukbb import write_tensors\n",
    "from ml4cvd.tensor_generators import test_train_valid_tensor_generators\n",
    "from ml4cvd.recipes import train_multimodal_multitask, test_multimodal_multitask\n",
    "from ml4cvd.models import make_multimodal_to_multilabel_model, train_model_from_generators\n",
    "\n",
    "%matplotlib inline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'5732608.hd5'"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "os.listdir('/mnt/disks/ecg-rest-and-bike-with-trend-tensors/2019-08-13/')[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2019-08-15 14:54:35,179 - logger:25 - INFO - Logging configuration was loaded. Log messages can be found at /home/ndiamant/ml/notebooks/recipes_output/ecg_sketch/ecg_bike_recovery_labeler/log_2019-08-15_14-54_0.log.\n",
      "2019-08-15 14:54:35,180 - arguments:180 - INFO - Command Line was:\n",
      "\n",
      "python train --tensors /mnt/disks/ecg-rest-and-bike-with-trend-tensors/2019-08-13/ --input_tensors ecg_bike_recovery --output_tensors ecg-bike-max-pred-hr-no0 ecg-bike-max-hr-no0 ecg-bike-resting-hr-no0 --batch_size 64 --epochs 20 --training_steps 5 --inspect_model --u_connect --learning_rate 0.01 --id ecg_bike_recovery_labeler --output_folder /home/ndiamant/ml/notebooks/recipes_output/ecg_sketch\n",
      "\n",
      "\n",
      "2019-08-15 14:54:35,181 - arguments:181 - INFO - Total TensorMaps:4414 Arguments are Namespace(activation='relu', aligned_dimension=16, alpha=0.5, app_csv=None, b_slice_force=None, balance_csvs=[], batch_size=64, bigquery_credentials_file='/mnt/ml4cvd/projects/jamesp/bigquery/bigquery-viewer-credentials.json', bigquery_dataset='broad-ml4cvd.ukbb7089_r10data', block_size=3, categorical_field_ids=[], continuous_field_ids=[], conv_bn=False, conv_dropout=0.0, conv_layers=[32], conv_width=71, conv_x=3, conv_y=3, conv_z=2, db='/mnt/disks/data/raw/sql/ukbb7089.r10data.db', debug=False, dense_blocks=[32, 24, 16], dense_layers=[16, 64], dicoms='./dicoms/', dropout=0.0, epochs=20, hidden_layer='embed', icd_csv='/mnt/ml4cvd/projects/jamesp/data/modified.zmerge.prs.full.csv.20190222', id='ecg_bike_recovery_labeler', imputation_method_for_continuous_fields='random', include_array=False, include_heart_zoom=False, include_instance=False, include_missing_continuous_channel=False, input_continuous_tensors=[], input_tensors=['ecg_bike_recovery'], inspect_model=True, inspect_show_labels=True, label_weights=None, learning_rate=0.01, logging_level='INFO', lv_mass_csv='/mnt/ml4cvd/projects/jamesp/data/returned_lv_mass.tsv', max_models=16, max_parameters=9000000, max_patients=999999, max_pools=[], max_sample_id=7000000, max_samples=None, max_slices=999999, min_sample_id=0, min_samples=3, min_values=10, mlp_concat=False, mode='mlp', model_file=None, model_files=[], model_freeze=None, model_layers=None, mri_field_ids=['20208', '20209'], output_folder='/home/ndiamant/ml/notebooks/recipes_output/ecg_sketch', output_tensors=['ecg-bike-max-pred-hr-no0', 'ecg-bike-max-hr-no0', 'ecg-bike-resting-hr-no0'], padding='same', patience=8, phecode_definitions='/mnt/ml4cvd/projects/jamesp/data/phecode_definitions1.2.csv', phenos_folder='/mnt/disks/data/raw/phenotypes/', pool_x=2, pool_y=2, pool_z=1, random_seed=12878, res_layers=[], t=48, tensor_maps_in=[<ml4cvd.TensorMap.TensorMap object at 0x7f8a15dc2470>], tensor_maps_out=[<ml4cvd.TensorMap.TensorMap object at 0x7f8a15dc2390>, <ml4cvd.TensorMap.TensorMap object at 0x7f8a15dc22b0>, <ml4cvd.TensorMap.TensorMap object at 0x7f8a15dc2320>], tensors='/mnt/disks/ecg-rest-and-bike-with-trend-tensors/2019-08-13/', test_modulo=10, test_ratio=0.1, test_steps=32, training_steps=5, u_connect=True, valid_ratio=0.2, validation_steps=40, volume_csv='/mnt/ml4cvd/projects/jamesp/data/cMRI_20190618_manual_qc.all.tsv', write_pngs=False, x=256, xml_field_ids=['20205', '6025'], xml_folder='/mnt/disks/ecg-rest-xml/', y=256, z=48, zip_folder='/mnt/disks/sax-mri-zip/', zoom_height=96, zoom_width=96, zoom_x=50, zoom_y=35)\n",
      "2019-08-15 14:54:36,092 - tensor_generators:274 - INFO - Found 52137 training, 7392 validation, and 23238 testing tensors at: /mnt/disks/ecg-rest-and-bike-with-trend-tensors/2019-08-13/\n"
     ]
    }
   ],
   "source": [
    "sys.argv = ['train', \n",
    "            '--tensors', '/mnt/disks/ecg-rest-and-bike-with-trend-tensors/2019-08-13/', \n",
    "            '--input_tensors', 'ecg_bike_recovery', \n",
    "            '--output_tensors','ecg-bike-max-pred-hr-no0', 'ecg-bike-max-hr-no0', 'ecg-bike-resting-hr-no0',\n",
    "            '--batch_size', '64', \n",
    "            '--epochs', '20',\n",
    "            '--training_steps', '5',\n",
    "            '--inspect_model',\n",
    "            '--u_connect',\n",
    "            '--learning_rate', '0.01',\n",
    "            '--id', 'ecg_bike_recovery_labeler',\n",
    "            '--output_folder', '/home/ndiamant/ml/notebooks/recipes_output/ecg_sketch'\n",
    "           ]\n",
    "args = parse_args()\n",
    "generate_train, generate_valid, generate_test = test_train_valid_tensor_generators(args.tensor_maps_in,  args.tensor_maps_out,  args.tensors, args.batch_size,   args.valid_ratio, args.test_ratio, args.test_modulo, args.balance_csvs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "__________________________________________________________________________________________________\n",
      "Layer (type)                    Output Shape         Param #     Connected to                     \n",
      "==================================================================================================\n",
      "input_full_ecg_bike_recovery (I (None, 30000, 3)     0                                            \n",
      "__________________________________________________________________________________________________\n",
      "conv1d_27 (Conv1D)              (None, 30000, 32)    6848        input_full_ecg_bike_recovery[0][0\n",
      "__________________________________________________________________________________________________\n",
      "conv1d_28 (Conv1D)              (None, 30000, 32)    72736       conv1d_27[0][0]                  \n",
      "__________________________________________________________________________________________________\n",
      "max_pooling1d_7 (MaxPooling1D)  (None, 15000, 32)    0           conv1d_28[0][0]                  \n",
      "__________________________________________________________________________________________________\n",
      "conv1d_30 (Conv1D)              (None, 15000, 32)    72736       max_pooling1d_7[0][0]            \n",
      "__________________________________________________________________________________________________\n",
      "concatenate_13 (Concatenate)    (None, 15000, 64)    0           max_pooling1d_7[0][0]            \n",
      "                                                                 conv1d_30[0][0]                  \n",
      "__________________________________________________________________________________________________\n",
      "conv1d_31 (Conv1D)              (None, 15000, 32)    145440      concatenate_13[0][0]             \n",
      "__________________________________________________________________________________________________\n",
      "concatenate_14 (Concatenate)    (None, 15000, 96)    0           max_pooling1d_7[0][0]            \n",
      "                                                                 conv1d_30[0][0]                  \n",
      "                                                                 conv1d_31[0][0]                  \n",
      "__________________________________________________________________________________________________\n",
      "conv1d_32 (Conv1D)              (None, 15000, 24)    163608      concatenate_14[0][0]             \n",
      "__________________________________________________________________________________________________\n",
      "max_pooling1d_8 (MaxPooling1D)  (None, 7500, 24)     0           conv1d_32[0][0]                  \n",
      "__________________________________________________________________________________________________\n",
      "conv1d_34 (Conv1D)              (None, 7500, 24)     40920       max_pooling1d_8[0][0]            \n",
      "__________________________________________________________________________________________________\n",
      "concatenate_15 (Concatenate)    (None, 7500, 48)     0           max_pooling1d_8[0][0]            \n",
      "                                                                 conv1d_34[0][0]                  \n",
      "__________________________________________________________________________________________________\n",
      "conv1d_35 (Conv1D)              (None, 7500, 24)     81816       concatenate_15[0][0]             \n",
      "__________________________________________________________________________________________________\n",
      "concatenate_16 (Concatenate)    (None, 7500, 72)     0           max_pooling1d_8[0][0]            \n",
      "                                                                 conv1d_34[0][0]                  \n",
      "                                                                 conv1d_35[0][0]                  \n",
      "__________________________________________________________________________________________________\n",
      "conv1d_36 (Conv1D)              (None, 7500, 16)     81808       concatenate_16[0][0]             \n",
      "__________________________________________________________________________________________________\n",
      "max_pooling1d_9 (MaxPooling1D)  (None, 3750, 16)     0           conv1d_36[0][0]                  \n",
      "__________________________________________________________________________________________________\n",
      "conv1d_38 (Conv1D)              (None, 3750, 16)     18192       max_pooling1d_9[0][0]            \n",
      "__________________________________________________________________________________________________\n",
      "concatenate_17 (Concatenate)    (None, 3750, 32)     0           max_pooling1d_9[0][0]            \n",
      "                                                                 conv1d_38[0][0]                  \n",
      "__________________________________________________________________________________________________\n",
      "conv1d_39 (Conv1D)              (None, 3750, 16)     36368       concatenate_17[0][0]             \n",
      "__________________________________________________________________________________________________\n",
      "concatenate_18 (Concatenate)    (None, 3750, 48)     0           max_pooling1d_9[0][0]            \n",
      "                                                                 conv1d_38[0][0]                  \n",
      "                                                                 conv1d_39[0][0]                  \n",
      "__________________________________________________________________________________________________\n",
      "flatten_3 (Flatten)             (None, 180000)       0           concatenate_18[0][0]             \n",
      "__________________________________________________________________________________________________\n",
      "dense_3 (Dense)                 (None, 16)           2880016     flatten_3[0][0]                  \n",
      "__________________________________________________________________________________________________\n",
      "embed (Dense)                   (None, 64)           1088        dense_3[0][0]                    \n",
      "__________________________________________________________________________________________________\n",
      "output_bike_max_pred_hr_continu (None, 1)            65          embed[0][0]                      \n",
      "__________________________________________________________________________________________________\n",
      "output_bike_max_hr_continuous ( (None, 1)            65          embed[0][0]                      \n",
      "__________________________________________________________________________________________________\n",
      "output_bike_resting_hr_continuo (None, 1)            65          embed[0][0]                      \n",
      "==================================================================================================\n",
      "Total params: 3,601,771\n",
      "Trainable params: 3,601,771\n",
      "Non-trainable params: 0\n",
      "__________________________________________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "model = make_multimodal_to_multilabel_model(args.model_file, args.model_layers, args.model_freeze,\n",
    "                                                args.tensor_maps_in, args.tensor_maps_out, args.activation,\n",
    "                                                args.dense_layers, args.dropout, args.mlp_concat, args.conv_layers,\n",
    "                                                args.max_pools, args.res_layers, args.dense_blocks, args.block_size,\n",
    "                                                args.conv_bn, args.conv_x, args.conv_y, args.conv_z, args.conv_dropout,\n",
    "                                                args.conv_width, args.u_connect, args.pool_x, args.pool_y, args.pool_z, args.padding,\n",
    "                                                args.learning_rate)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "# model.predict_generator(generate_test, steps=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2019-08-15 14:54:40,326 - models:852 - INFO - Saving architecture diagram to:/home/ndiamant/ml/notebooks/recipes_output/ecg_sketch/ecg_bike_recovery_labeler/architecture_graph_ecg_bike_recovery_labeler.png\n",
      "Epoch 1/1\n",
      "2019-08-15 14:54:43,117 - tensor_generators:372 - INFO - Got first error: KeyError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 80, in multimodal_multitask_generator\n",
      "    in_batch[tm.input_name()][stats['batch_index']] = tm.tensor_from_file(hd5, dependents)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 625, in tensor_from_file\n",
      "    tensor[:, idx] = hd5[self.group][channel]\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py\", line 262, in __getitem__\n",
      "    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/h5o.pyx\", line 190, in h5py.h5o.open\n",
      "KeyError: \"Unable to open object (object 'ecg_bike_recovery' doesn't exist)\"\n",
      "\n",
      "\n",
      "2019-08-15 14:54:43,119 - tensor_generators:373 - INFO - At tensor path: /mnt/disks/ecg-rest-and-bike-with-trend-tensors/2019-08-13/5732608.hd5\n",
      "2019-08-15 14:54:43,303 - tensor_generators:372 - INFO - Got first error: KeyError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 80, in multimodal_multitask_generator\n",
      "    in_batch[tm.input_name()][stats['batch_index']] = tm.tensor_from_file(hd5, dependents)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 625, in tensor_from_file\n",
      "    tensor[:, idx] = hd5[self.group][channel]\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py\", line 262, in __getitem__\n",
      "    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/h5o.pyx\", line 190, in h5py.h5o.open\n",
      "KeyError: \"Unable to open object (object 'ecg_bike_recovery' doesn't exist)\"\n",
      "\n",
      "\n",
      "2019-08-15 14:54:43,306 - tensor_generators:373 - INFO - At tensor path: /mnt/disks/ecg-rest-and-bike-with-trend-tensors/2019-08-13/2321462.hd5\n",
      "2019-08-15 14:54:48,230 - tensor_generators:372 - INFO - Got first error: ValueError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 86, in multimodal_multitask_generator\n",
      "    out_batch[tm.output_name()][stats['batch_index']] = tm.tensor_from_file(hd5)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 564, in tensor_from_file\n",
      "    raise ValueError(self.name + ' is a continuous value that cannot be set to 0, but no value was found.')\n",
      "ValueError: bike_resting_hr is a continuous value that cannot be set to 0, but no value was found.\n",
      "\n",
      "\n",
      "2019-08-15 14:54:48,232 - tensor_generators:373 - INFO - At tensor path: /mnt/disks/ecg-rest-and-bike-with-trend-tensors/2019-08-13/3358738.hd5\n",
      "5/5 [==============================] - 19s 4s/step - loss: 303792.8910 - output_bike_max_pred_hr_continuous_loss: 145836.1821 - output_bike_max_hr_continuous_loss: 60181.5106 - output_bike_resting_hr_continuous_loss: 97775.1857 - output_bike_max_pred_hr_continuous_logcosh: 145836.1821 - output_bike_max_hr_continuous_logcosh: 60181.5106 - output_bike_resting_hr_continuous_logcosh: 97775.1857 - val_loss: 1.0039 - val_output_bike_max_pred_hr_continuous_loss: 0.3958 - val_output_bike_max_hr_continuous_loss: 0.2460 - val_output_bike_resting_hr_continuous_loss: 0.3621 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3958 - val_output_bike_max_hr_continuous_logcosh: 0.2460 - val_output_bike_resting_hr_continuous_logcosh: 0.3621\n",
      "2019-08-15 14:55:02,061 - models:789 - INFO - Spent:21.226847648620605 seconds training, batch_size:64 steps:5 Per example training speed:0.06633389890193939\n",
      "5/5 [==============================] - 5s 1s/step\n",
      "2019-08-15 14:55:07,211 - models:795 - INFO - Spent:5.147967576980591 seconds predicting. Per tensor inference speed:0.016087398678064347\n",
      "Epoch 1/20\n",
      "3/5 [=================>............] - ETA: 4s - loss: 1.1966 - output_bike_max_pred_hr_continuous_loss: 0.4959 - output_bike_max_hr_continuous_loss: 0.2899 - output_bike_resting_hr_continuous_loss: 0.4108 - output_bike_max_pred_hr_continuous_logcosh: 0.4959 - output_bike_max_hr_continuous_logcosh: 0.2899 - output_bike_resting_hr_continuous_logcosh: 0.41082019-08-15 14:55:14,018 - tensor_generators:372 - INFO - Got first error: ValueError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 86, in multimodal_multitask_generator\n",
      "    out_batch[tm.output_name()][stats['batch_index']] = tm.tensor_from_file(hd5)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 564, in tensor_from_file\n",
      "    raise ValueError(self.name + ' is a continuous value that cannot be set to 0, but no value was found.')\n",
      "ValueError: bike_resting_hr is a continuous value that cannot be set to 0, but no value was found.\n",
      "\n",
      "\n",
      "2019-08-15 14:55:14,019 - tensor_generators:373 - INFO - At tensor path: /mnt/disks/ecg-rest-and-bike-with-trend-tensors/2019-08-13/1623979.hd5\n",
      "5/5 [==============================] - 32s 6s/step - loss: 1.1259 - output_bike_max_pred_hr_continuous_loss: 0.4256 - output_bike_max_hr_continuous_loss: 0.2887 - output_bike_resting_hr_continuous_loss: 0.4116 - output_bike_max_pred_hr_continuous_logcosh: 0.4256 - output_bike_max_hr_continuous_logcosh: 0.2887 - output_bike_resting_hr_continuous_logcosh: 0.4116 - val_loss: 0.9561 - val_output_bike_max_pred_hr_continuous_loss: 0.3686 - val_output_bike_max_hr_continuous_loss: 0.2449 - val_output_bike_resting_hr_continuous_loss: 0.3425 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3686 - val_output_bike_max_hr_continuous_logcosh: 0.2449 - val_output_bike_resting_hr_continuous_logcosh: 0.3425\n",
      "\n",
      "Epoch 00001: val_loss improved from inf to 0.95606, saving model to /home/ndiamant/ml/notebooks/recipes_output/ecg_sketch/ecg_bike_recovery_labeler/ecg_bike_recovery_labeler.hd5\n",
      "Epoch 2/20\n",
      "4/5 [=======================>......] - ETA: 1s - loss: 0.9932 - output_bike_max_pred_hr_continuous_loss: 0.4003 - output_bike_max_hr_continuous_loss: 0.2529 - output_bike_resting_hr_continuous_loss: 0.3400 - output_bike_max_pred_hr_continuous_logcosh: 0.4003 - output_bike_max_hr_continuous_logcosh: 0.2529 - output_bike_resting_hr_continuous_logcosh: 0.34002019-08-15 14:55:55,790 - tensor_generators:114 - INFO - batch_index: 7\n",
      "2019-08-15 14:55:55,791 - tensor_generators:114 - INFO - Tensors presented: 4999\n",
      "2019-08-15 14:55:55,796 - tensor_generators:114 - INFO - KeyError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 80, in multimodal_multitask_generator\n",
      "    in_batch[tm.input_name()][stats['batch_index']] = tm.tensor_from_file(hd5, dependents)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 625, in tensor_from_file\n",
      "    tensor[:, idx] = hd5[self.group][channel]\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py\", line 262, in __getitem__\n",
      "    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/h5o.pyx\", line 190, in h5py.h5o.open\n",
      "KeyError: \"Unable to open object (object 'ecg_bike_recovery' doesn't exist)\"\n",
      "\n",
      ": 2389\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2019-08-15 14:55:55,797 - tensor_generators:114 - INFO - ValueError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 86, in multimodal_multitask_generator\n",
      "    out_batch[tm.output_name()][stats['batch_index']] = tm.tensor_from_file(hd5)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 564, in tensor_from_file\n",
      "    raise ValueError(self.name + ' is a continuous value that cannot be set to 0, but no value was found.')\n",
      "ValueError: bike_resting_hr is a continuous value that cannot be set to 0, but no value was found.\n",
      "\n",
      ": 6\n",
      "2019-08-15 14:55:55,798 - tensor_generators:114 - INFO - epochs: 1\n",
      "2019-08-15 14:55:55,800 - tensor_generators:115 - INFO - Generator looped & shuffled over 7392 tensors.\n",
      "2019-08-15 14:55:55,802 - tensor_generators:116 - INFO - True epoch number:1 in which 4999 tensors were presented.\n",
      "5/5 [==============================] - 20s 4s/step - loss: 1.0272 - output_bike_max_pred_hr_continuous_loss: 0.4051 - output_bike_max_hr_continuous_loss: 0.2659 - output_bike_resting_hr_continuous_loss: 0.3562 - output_bike_max_pred_hr_continuous_logcosh: 0.4051 - output_bike_max_hr_continuous_logcosh: 0.2659 - output_bike_resting_hr_continuous_logcosh: 0.3562 - val_loss: 0.9921 - val_output_bike_max_pred_hr_continuous_loss: 0.4047 - val_output_bike_max_hr_continuous_loss: 0.2479 - val_output_bike_resting_hr_continuous_loss: 0.3395 - val_output_bike_max_pred_hr_continuous_logcosh: 0.4047 - val_output_bike_max_hr_continuous_logcosh: 0.2479 - val_output_bike_resting_hr_continuous_logcosh: 0.3395\n",
      "\n",
      "Epoch 00002: val_loss did not improve from 0.95606\n",
      "Epoch 3/20\n",
      "5/5 [==============================] - 20s 4s/step - loss: 1.0767 - output_bike_max_pred_hr_continuous_loss: 0.4212 - output_bike_max_hr_continuous_loss: 0.2293 - output_bike_resting_hr_continuous_loss: 0.4263 - output_bike_max_pred_hr_continuous_logcosh: 0.4212 - output_bike_max_hr_continuous_logcosh: 0.2293 - output_bike_resting_hr_continuous_logcosh: 0.4263 - val_loss: 0.9677 - val_output_bike_max_pred_hr_continuous_loss: 0.3944 - val_output_bike_max_hr_continuous_loss: 0.2416 - val_output_bike_resting_hr_continuous_loss: 0.3317 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3944 - val_output_bike_max_hr_continuous_logcosh: 0.2416 - val_output_bike_resting_hr_continuous_logcosh: 0.3317\n",
      "\n",
      "Epoch 00003: val_loss did not improve from 0.95606\n",
      "Epoch 4/20\n",
      "4/5 [=======================>......] - ETA: 1s - loss: 0.9193 - output_bike_max_pred_hr_continuous_loss: 0.4052 - output_bike_max_hr_continuous_loss: 0.2124 - output_bike_resting_hr_continuous_loss: 0.3017 - output_bike_max_pred_hr_continuous_logcosh: 0.4052 - output_bike_max_hr_continuous_logcosh: 0.2124 - output_bike_resting_hr_continuous_logcosh: 0.30172019-08-15 14:56:34,717 - tensor_generators:114 - INFO - batch_index: 14\n",
      "2019-08-15 14:56:34,718 - tensor_generators:114 - INFO - Tensors presented: 9998\n",
      "2019-08-15 14:56:34,721 - tensor_generators:114 - INFO - KeyError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 80, in multimodal_multitask_generator\n",
      "    in_batch[tm.input_name()][stats['batch_index']] = tm.tensor_from_file(hd5, dependents)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 625, in tensor_from_file\n",
      "    tensor[:, idx] = hd5[self.group][channel]\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py\", line 262, in __getitem__\n",
      "    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/h5o.pyx\", line 190, in h5py.h5o.open\n",
      "KeyError: \"Unable to open object (object 'ecg_bike_recovery' doesn't exist)\"\n",
      "\n",
      ": 4777\n",
      "2019-08-15 14:56:34,724 - tensor_generators:114 - INFO - ValueError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 86, in multimodal_multitask_generator\n",
      "    out_batch[tm.output_name()][stats['batch_index']] = tm.tensor_from_file(hd5)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 564, in tensor_from_file\n",
      "    raise ValueError(self.name + ' is a continuous value that cannot be set to 0, but no value was found.')\n",
      "ValueError: bike_resting_hr is a continuous value that cannot be set to 0, but no value was found.\n",
      "\n",
      ": 11\n",
      "2019-08-15 14:56:34,725 - tensor_generators:114 - INFO - epochs: 2\n",
      "2019-08-15 14:56:34,726 - tensor_generators:115 - INFO - Generator looped & shuffled over 7392 tensors.\n",
      "2019-08-15 14:56:34,727 - tensor_generators:116 - INFO - True epoch number:2 in which 4999 tensors were presented.\n",
      "5/5 [==============================] - 20s 4s/step - loss: 0.9429 - output_bike_max_pred_hr_continuous_loss: 0.4065 - output_bike_max_hr_continuous_loss: 0.2166 - output_bike_resting_hr_continuous_loss: 0.3198 - output_bike_max_pred_hr_continuous_logcosh: 0.4065 - output_bike_max_hr_continuous_logcosh: 0.2166 - output_bike_resting_hr_continuous_logcosh: 0.3198 - val_loss: 1.0377 - val_output_bike_max_pred_hr_continuous_loss: 0.4055 - val_output_bike_max_hr_continuous_loss: 0.2789 - val_output_bike_resting_hr_continuous_loss: 0.3533 - val_output_bike_max_pred_hr_continuous_logcosh: 0.4055 - val_output_bike_max_hr_continuous_logcosh: 0.2789 - val_output_bike_resting_hr_continuous_logcosh: 0.3533\n",
      "\n",
      "Epoch 00004: val_loss did not improve from 0.95606\n",
      "Epoch 5/20\n",
      "5/5 [==============================] - 20s 4s/step - loss: 0.9293 - output_bike_max_pred_hr_continuous_loss: 0.3847 - output_bike_max_hr_continuous_loss: 0.2210 - output_bike_resting_hr_continuous_loss: 0.3237 - output_bike_max_pred_hr_continuous_logcosh: 0.3847 - output_bike_max_hr_continuous_logcosh: 0.2210 - output_bike_resting_hr_continuous_logcosh: 0.3237 - val_loss: 0.9705 - val_output_bike_max_pred_hr_continuous_loss: 0.3986 - val_output_bike_max_hr_continuous_loss: 0.2393 - val_output_bike_resting_hr_continuous_loss: 0.3325 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3986 - val_output_bike_max_hr_continuous_logcosh: 0.2393 - val_output_bike_resting_hr_continuous_logcosh: 0.3325\n",
      "\n",
      "Epoch 00005: val_loss did not improve from 0.95606\n",
      "Epoch 6/20\n",
      "4/5 [=======================>......] - ETA: 1s - loss: 1.0671 - output_bike_max_pred_hr_continuous_loss: 0.4140 - output_bike_max_hr_continuous_loss: 0.2576 - output_bike_resting_hr_continuous_loss: 0.3954 - output_bike_max_pred_hr_continuous_logcosh: 0.4140 - output_bike_max_hr_continuous_logcosh: 0.2576 - output_bike_resting_hr_continuous_logcosh: 0.39542019-08-15 14:57:14,342 - tensor_generators:114 - INFO - batch_index: 21\n",
      "2019-08-15 14:57:14,343 - tensor_generators:114 - INFO - Tensors presented: 14997\n",
      "2019-08-15 14:57:14,347 - tensor_generators:114 - INFO - KeyError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 80, in multimodal_multitask_generator\n",
      "    in_batch[tm.input_name()][stats['batch_index']] = tm.tensor_from_file(hd5, dependents)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 625, in tensor_from_file\n",
      "    tensor[:, idx] = hd5[self.group][channel]\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py\", line 262, in __getitem__\n",
      "    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/h5o.pyx\", line 190, in h5py.h5o.open\n",
      "KeyError: \"Unable to open object (object 'ecg_bike_recovery' doesn't exist)\"\n",
      "\n",
      ": 7165\n",
      "2019-08-15 14:57:14,348 - tensor_generators:114 - INFO - ValueError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 86, in multimodal_multitask_generator\n",
      "    out_batch[tm.output_name()][stats['batch_index']] = tm.tensor_from_file(hd5)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 564, in tensor_from_file\n",
      "    raise ValueError(self.name + ' is a continuous value that cannot be set to 0, but no value was found.')\n",
      "ValueError: bike_resting_hr is a continuous value that cannot be set to 0, but no value was found.\n",
      "\n",
      ": 16\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2019-08-15 14:57:14,349 - tensor_generators:114 - INFO - epochs: 3\n",
      "2019-08-15 14:57:14,350 - tensor_generators:115 - INFO - Generator looped & shuffled over 7392 tensors.\n",
      "2019-08-15 14:57:14,352 - tensor_generators:116 - INFO - True epoch number:3 in which 4999 tensors were presented.\n",
      "5/5 [==============================] - 20s 4s/step - loss: 1.0414 - output_bike_max_pred_hr_continuous_loss: 0.4031 - output_bike_max_hr_continuous_loss: 0.2531 - output_bike_resting_hr_continuous_loss: 0.3851 - output_bike_max_pred_hr_continuous_logcosh: 0.4031 - output_bike_max_hr_continuous_logcosh: 0.2531 - output_bike_resting_hr_continuous_logcosh: 0.3851 - val_loss: 0.9480 - val_output_bike_max_pred_hr_continuous_loss: 0.3863 - val_output_bike_max_hr_continuous_loss: 0.2422 - val_output_bike_resting_hr_continuous_loss: 0.3195 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3863 - val_output_bike_max_hr_continuous_logcosh: 0.2422 - val_output_bike_resting_hr_continuous_logcosh: 0.3195\n",
      "\n",
      "Epoch 00006: val_loss improved from 0.95606 to 0.94797, saving model to /home/ndiamant/ml/notebooks/recipes_output/ecg_sketch/ecg_bike_recovery_labeler/ecg_bike_recovery_labeler.hd5\n",
      "Epoch 7/20\n",
      "5/5 [==============================] - 21s 4s/step - loss: 1.0470 - output_bike_max_pred_hr_continuous_loss: 0.3915 - output_bike_max_hr_continuous_loss: 0.2680 - output_bike_resting_hr_continuous_loss: 0.3875 - output_bike_max_pred_hr_continuous_logcosh: 0.3915 - output_bike_max_hr_continuous_logcosh: 0.2680 - output_bike_resting_hr_continuous_logcosh: 0.3875 - val_loss: 0.9774 - val_output_bike_max_pred_hr_continuous_loss: 0.3874 - val_output_bike_max_hr_continuous_loss: 0.2334 - val_output_bike_resting_hr_continuous_loss: 0.3567 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3874 - val_output_bike_max_hr_continuous_logcosh: 0.2334 - val_output_bike_resting_hr_continuous_logcosh: 0.3567\n",
      "\n",
      "Epoch 00007: val_loss did not improve from 0.94797\n",
      "Epoch 8/20\n",
      "2/5 [===========>..................] - ETA: 4s - loss: 0.9840 - output_bike_max_pred_hr_continuous_loss: 0.4139 - output_bike_max_hr_continuous_loss: 0.2164 - output_bike_resting_hr_continuous_loss: 0.3537 - output_bike_max_pred_hr_continuous_logcosh: 0.4139 - output_bike_max_hr_continuous_logcosh: 0.2164 - output_bike_resting_hr_continuous_logcosh: 0.35372019-08-15 14:57:53,107 - tensor_generators:114 - INFO - batch_index: 28\n",
      "2019-08-15 14:57:53,108 - tensor_generators:114 - INFO - Tensors presented: 19996\n",
      "2019-08-15 14:57:53,110 - tensor_generators:114 - INFO - KeyError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 80, in multimodal_multitask_generator\n",
      "    in_batch[tm.input_name()][stats['batch_index']] = tm.tensor_from_file(hd5, dependents)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 625, in tensor_from_file\n",
      "    tensor[:, idx] = hd5[self.group][channel]\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py\", line 262, in __getitem__\n",
      "    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/h5o.pyx\", line 190, in h5py.h5o.open\n",
      "KeyError: \"Unable to open object (object 'ecg_bike_recovery' doesn't exist)\"\n",
      "\n",
      ": 9553\n",
      "2019-08-15 14:57:53,112 - tensor_generators:114 - INFO - ValueError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 86, in multimodal_multitask_generator\n",
      "    out_batch[tm.output_name()][stats['batch_index']] = tm.tensor_from_file(hd5)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 564, in tensor_from_file\n",
      "    raise ValueError(self.name + ' is a continuous value that cannot be set to 0, but no value was found.')\n",
      "ValueError: bike_resting_hr is a continuous value that cannot be set to 0, but no value was found.\n",
      "\n",
      ": 21\n",
      "2019-08-15 14:57:53,113 - tensor_generators:114 - INFO - epochs: 4\n",
      "2019-08-15 14:57:53,114 - tensor_generators:115 - INFO - Generator looped & shuffled over 7392 tensors.\n",
      "2019-08-15 14:57:53,115 - tensor_generators:116 - INFO - True epoch number:4 in which 4999 tensors were presented.\n",
      "5/5 [==============================] - 20s 4s/step - loss: 0.9046 - output_bike_max_pred_hr_continuous_loss: 0.3912 - output_bike_max_hr_continuous_loss: 0.1945 - output_bike_resting_hr_continuous_loss: 0.3189 - output_bike_max_pred_hr_continuous_logcosh: 0.3912 - output_bike_max_hr_continuous_logcosh: 0.1945 - output_bike_resting_hr_continuous_logcosh: 0.3189 - val_loss: 0.9783 - val_output_bike_max_pred_hr_continuous_loss: 0.4015 - val_output_bike_max_hr_continuous_loss: 0.2358 - val_output_bike_resting_hr_continuous_loss: 0.3410 - val_output_bike_max_pred_hr_continuous_logcosh: 0.4015 - val_output_bike_max_hr_continuous_logcosh: 0.2358 - val_output_bike_resting_hr_continuous_logcosh: 0.3410\n",
      "\n",
      "Epoch 00008: val_loss did not improve from 0.94797\n",
      "Epoch 9/20\n",
      "5/5 [==============================] - 20s 4s/step - loss: 0.9432 - output_bike_max_pred_hr_continuous_loss: 0.3659 - output_bike_max_hr_continuous_loss: 0.2369 - output_bike_resting_hr_continuous_loss: 0.3404 - output_bike_max_pred_hr_continuous_logcosh: 0.3659 - output_bike_max_hr_continuous_logcosh: 0.2369 - output_bike_resting_hr_continuous_logcosh: 0.3404 - val_loss: 0.9457 - val_output_bike_max_pred_hr_continuous_loss: 0.3810 - val_output_bike_max_hr_continuous_loss: 0.2275 - val_output_bike_resting_hr_continuous_loss: 0.3371 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3810 - val_output_bike_max_hr_continuous_logcosh: 0.2275 - val_output_bike_resting_hr_continuous_logcosh: 0.3371\n",
      "\n",
      "Epoch 00009: val_loss improved from 0.94797 to 0.94566, saving model to /home/ndiamant/ml/notebooks/recipes_output/ecg_sketch/ecg_bike_recovery_labeler/ecg_bike_recovery_labeler.hd5\n",
      "Epoch 10/20\n",
      "2/5 [===========>..................] - ETA: 4s - loss: 0.9347 - output_bike_max_pred_hr_continuous_loss: 0.4286 - output_bike_max_hr_continuous_loss: 0.2349 - output_bike_resting_hr_continuous_loss: 0.2713 - output_bike_max_pred_hr_continuous_logcosh: 0.4286 - output_bike_max_hr_continuous_logcosh: 0.2349 - output_bike_resting_hr_continuous_logcosh: 0.27132019-08-15 14:58:33,040 - tensor_generators:114 - INFO - batch_index: 35\n",
      "2019-08-15 14:58:33,042 - tensor_generators:114 - INFO - Tensors presented: 24995\n",
      "2019-08-15 14:58:33,044 - tensor_generators:114 - INFO - KeyError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 80, in multimodal_multitask_generator\n",
      "    in_batch[tm.input_name()][stats['batch_index']] = tm.tensor_from_file(hd5, dependents)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 625, in tensor_from_file\n",
      "    tensor[:, idx] = hd5[self.group][channel]\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py\", line 262, in __getitem__\n",
      "    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/h5o.pyx\", line 190, in h5py.h5o.open\n",
      "KeyError: \"Unable to open object (object 'ecg_bike_recovery' doesn't exist)\"\n",
      "\n",
      ": 11941\n",
      "2019-08-15 14:58:33,045 - tensor_generators:114 - INFO - ValueError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 86, in multimodal_multitask_generator\n",
      "    out_batch[tm.output_name()][stats['batch_index']] = tm.tensor_from_file(hd5)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 564, in tensor_from_file\n",
      "    raise ValueError(self.name + ' is a continuous value that cannot be set to 0, but no value was found.')\n",
      "ValueError: bike_resting_hr is a continuous value that cannot be set to 0, but no value was found.\n",
      "\n",
      ": 26\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2019-08-15 14:58:33,046 - tensor_generators:114 - INFO - epochs: 5\n",
      "2019-08-15 14:58:33,048 - tensor_generators:115 - INFO - Generator looped & shuffled over 7392 tensors.\n",
      "2019-08-15 14:58:33,049 - tensor_generators:116 - INFO - True epoch number:5 in which 4999 tensors were presented.\n",
      "5/5 [==============================] - 20s 4s/step - loss: 0.9545 - output_bike_max_pred_hr_continuous_loss: 0.4100 - output_bike_max_hr_continuous_loss: 0.2285 - output_bike_resting_hr_continuous_loss: 0.3160 - output_bike_max_pred_hr_continuous_logcosh: 0.4100 - output_bike_max_hr_continuous_logcosh: 0.2285 - output_bike_resting_hr_continuous_logcosh: 0.3160 - val_loss: 0.9749 - val_output_bike_max_pred_hr_continuous_loss: 0.3851 - val_output_bike_max_hr_continuous_loss: 0.2414 - val_output_bike_resting_hr_continuous_loss: 0.3484 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3851 - val_output_bike_max_hr_continuous_logcosh: 0.2414 - val_output_bike_resting_hr_continuous_logcosh: 0.3484\n",
      "\n",
      "Epoch 00010: val_loss did not improve from 0.94566\n",
      "Epoch 11/20\n",
      "5/5 [==============================] - 20s 4s/step - loss: 0.9130 - output_bike_max_pred_hr_continuous_loss: 0.3764 - output_bike_max_hr_continuous_loss: 0.2210 - output_bike_resting_hr_continuous_loss: 0.3156 - output_bike_max_pred_hr_continuous_logcosh: 0.3764 - output_bike_max_hr_continuous_logcosh: 0.2210 - output_bike_resting_hr_continuous_logcosh: 0.3156 - val_loss: 0.9597 - val_output_bike_max_pred_hr_continuous_loss: 0.3956 - val_output_bike_max_hr_continuous_loss: 0.2313 - val_output_bike_resting_hr_continuous_loss: 0.3328 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3956 - val_output_bike_max_hr_continuous_logcosh: 0.2313 - val_output_bike_resting_hr_continuous_logcosh: 0.3328\n",
      "\n",
      "Epoch 00011: val_loss did not improve from 0.94566\n",
      "Epoch 12/20\n",
      "1/5 [=====>........................] - ETA: 6s - loss: 1.0937 - output_bike_max_pred_hr_continuous_loss: 0.3593 - output_bike_max_hr_continuous_loss: 0.3218 - output_bike_resting_hr_continuous_loss: 0.4125 - output_bike_max_pred_hr_continuous_logcosh: 0.3593 - output_bike_max_hr_continuous_logcosh: 0.3218 - output_bike_resting_hr_continuous_logcosh: 0.41252019-08-15 14:59:11,993 - tensor_generators:114 - INFO - batch_index: 42\n",
      "2019-08-15 14:59:11,994 - tensor_generators:114 - INFO - Tensors presented: 29994\n",
      "2019-08-15 14:59:11,995 - tensor_generators:114 - INFO - KeyError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 80, in multimodal_multitask_generator\n",
      "    in_batch[tm.input_name()][stats['batch_index']] = tm.tensor_from_file(hd5, dependents)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 625, in tensor_from_file\n",
      "    tensor[:, idx] = hd5[self.group][channel]\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py\", line 262, in __getitem__\n",
      "    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/h5o.pyx\", line 190, in h5py.h5o.open\n",
      "KeyError: \"Unable to open object (object 'ecg_bike_recovery' doesn't exist)\"\n",
      "\n",
      ": 14329\n",
      "2019-08-15 14:59:11,996 - tensor_generators:114 - INFO - ValueError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 86, in multimodal_multitask_generator\n",
      "    out_batch[tm.output_name()][stats['batch_index']] = tm.tensor_from_file(hd5)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 564, in tensor_from_file\n",
      "    raise ValueError(self.name + ' is a continuous value that cannot be set to 0, but no value was found.')\n",
      "ValueError: bike_resting_hr is a continuous value that cannot be set to 0, but no value was found.\n",
      "\n",
      ": 31\n",
      "2019-08-15 14:59:11,998 - tensor_generators:114 - INFO - epochs: 6\n",
      "2019-08-15 14:59:11,999 - tensor_generators:115 - INFO - Generator looped & shuffled over 7392 tensors.\n",
      "2019-08-15 14:59:12,000 - tensor_generators:116 - INFO - True epoch number:6 in which 4999 tensors were presented.\n",
      "5/5 [==============================] - 20s 4s/step - loss: 1.0917 - output_bike_max_pred_hr_continuous_loss: 0.4171 - output_bike_max_hr_continuous_loss: 0.2753 - output_bike_resting_hr_continuous_loss: 0.3992 - output_bike_max_pred_hr_continuous_logcosh: 0.4171 - output_bike_max_hr_continuous_logcosh: 0.2753 - output_bike_resting_hr_continuous_logcosh: 0.3992 - val_loss: 0.9356 - val_output_bike_max_pred_hr_continuous_loss: 0.3820 - val_output_bike_max_hr_continuous_loss: 0.2231 - val_output_bike_resting_hr_continuous_loss: 0.3304 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3820 - val_output_bike_max_hr_continuous_logcosh: 0.2231 - val_output_bike_resting_hr_continuous_logcosh: 0.3304\n",
      "\n",
      "Epoch 00012: val_loss improved from 0.94566 to 0.93558, saving model to /home/ndiamant/ml/notebooks/recipes_output/ecg_sketch/ecg_bike_recovery_labeler/ecg_bike_recovery_labeler.hd5\n",
      "Epoch 13/20\n",
      "5/5 [==============================] - 20s 4s/step - loss: 0.9830 - output_bike_max_pred_hr_continuous_loss: 0.4371 - output_bike_max_hr_continuous_loss: 0.1955 - output_bike_resting_hr_continuous_loss: 0.3505 - output_bike_max_pred_hr_continuous_logcosh: 0.4371 - output_bike_max_hr_continuous_logcosh: 0.1955 - output_bike_resting_hr_continuous_logcosh: 0.3505 - val_loss: 0.9723 - val_output_bike_max_pred_hr_continuous_loss: 0.3893 - val_output_bike_max_hr_continuous_loss: 0.2422 - val_output_bike_resting_hr_continuous_loss: 0.3408 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3893 - val_output_bike_max_hr_continuous_logcosh: 0.2422 - val_output_bike_resting_hr_continuous_logcosh: 0.3408\n",
      "\n",
      "Epoch 00013: val_loss did not improve from 0.93558\n",
      "Epoch 14/20\n",
      "1/5 [=====>........................] - ETA: 6s - loss: 1.0690 - output_bike_max_pred_hr_continuous_loss: 0.4286 - output_bike_max_hr_continuous_loss: 0.2282 - output_bike_resting_hr_continuous_loss: 0.4122 - output_bike_max_pred_hr_continuous_logcosh: 0.4286 - output_bike_max_hr_continuous_logcosh: 0.2282 - output_bike_resting_hr_continuous_logcosh: 0.41222019-08-15 14:59:52,106 - tensor_generators:114 - INFO - batch_index: 49\n",
      "2019-08-15 14:59:52,109 - tensor_generators:114 - INFO - Tensors presented: 34993\n",
      "2019-08-15 14:59:52,122 - tensor_generators:114 - INFO - KeyError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 80, in multimodal_multitask_generator\n",
      "    in_batch[tm.input_name()][stats['batch_index']] = tm.tensor_from_file(hd5, dependents)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 625, in tensor_from_file\n",
      "    tensor[:, idx] = hd5[self.group][channel]\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py\", line 262, in __getitem__\n",
      "    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/h5o.pyx\", line 190, in h5py.h5o.open\n",
      "KeyError: \"Unable to open object (object 'ecg_bike_recovery' doesn't exist)\"\n",
      "\n",
      ": 16717\n",
      "2019-08-15 14:59:52,130 - tensor_generators:114 - INFO - ValueError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 86, in multimodal_multitask_generator\n",
      "    out_batch[tm.output_name()][stats['batch_index']] = tm.tensor_from_file(hd5)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 564, in tensor_from_file\n",
      "    raise ValueError(self.name + ' is a continuous value that cannot be set to 0, but no value was found.')\n",
      "ValueError: bike_resting_hr is a continuous value that cannot be set to 0, but no value was found.\n",
      "\n",
      ": 36\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2019-08-15 14:59:52,139 - tensor_generators:114 - INFO - epochs: 7\n",
      "2019-08-15 14:59:52,141 - tensor_generators:115 - INFO - Generator looped & shuffled over 7392 tensors.\n",
      "2019-08-15 14:59:52,147 - tensor_generators:116 - INFO - True epoch number:7 in which 4999 tensors were presented.\n",
      "5/5 [==============================] - 21s 4s/step - loss: 0.9772 - output_bike_max_pred_hr_continuous_loss: 0.3940 - output_bike_max_hr_continuous_loss: 0.2436 - output_bike_resting_hr_continuous_loss: 0.3395 - output_bike_max_pred_hr_continuous_logcosh: 0.3940 - output_bike_max_hr_continuous_logcosh: 0.2436 - output_bike_resting_hr_continuous_logcosh: 0.3395 - val_loss: 0.9685 - val_output_bike_max_pred_hr_continuous_loss: 0.3910 - val_output_bike_max_hr_continuous_loss: 0.2346 - val_output_bike_resting_hr_continuous_loss: 0.3429 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3910 - val_output_bike_max_hr_continuous_logcosh: 0.2346 - val_output_bike_resting_hr_continuous_logcosh: 0.3429\n",
      "\n",
      "Epoch 00014: val_loss did not improve from 0.93558\n",
      "Epoch 15/20\n",
      "5/5 [==============================] - 20s 4s/step - loss: 0.9094 - output_bike_max_pred_hr_continuous_loss: 0.3504 - output_bike_max_hr_continuous_loss: 0.2058 - output_bike_resting_hr_continuous_loss: 0.3533 - output_bike_max_pred_hr_continuous_logcosh: 0.3504 - output_bike_max_hr_continuous_logcosh: 0.2058 - output_bike_resting_hr_continuous_logcosh: 0.3533 - val_loss: 0.9462 - val_output_bike_max_pred_hr_continuous_loss: 0.3810 - val_output_bike_max_hr_continuous_loss: 0.2347 - val_output_bike_resting_hr_continuous_loss: 0.3305 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3810 - val_output_bike_max_hr_continuous_logcosh: 0.2347 - val_output_bike_resting_hr_continuous_logcosh: 0.3305\n",
      "\n",
      "Epoch 00015: val_loss did not improve from 0.93558\n",
      "Epoch 16/20\n",
      "2019-08-15 15:00:32,219 - tensor_generators:114 - INFO - batch_index: 56\n",
      "2019-08-15 15:00:32,221 - tensor_generators:114 - INFO - Tensors presented: 39992\n",
      "2019-08-15 15:00:32,222 - tensor_generators:114 - INFO - KeyError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 80, in multimodal_multitask_generator\n",
      "    in_batch[tm.input_name()][stats['batch_index']] = tm.tensor_from_file(hd5, dependents)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 625, in tensor_from_file\n",
      "    tensor[:, idx] = hd5[self.group][channel]\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py\", line 262, in __getitem__\n",
      "    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/h5o.pyx\", line 190, in h5py.h5o.open\n",
      "KeyError: \"Unable to open object (object 'ecg_bike_recovery' doesn't exist)\"\n",
      "\n",
      ": 19105\n",
      "2019-08-15 15:00:32,223 - tensor_generators:114 - INFO - ValueError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 86, in multimodal_multitask_generator\n",
      "    out_batch[tm.output_name()][stats['batch_index']] = tm.tensor_from_file(hd5)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 564, in tensor_from_file\n",
      "    raise ValueError(self.name + ' is a continuous value that cannot be set to 0, but no value was found.')\n",
      "ValueError: bike_resting_hr is a continuous value that cannot be set to 0, but no value was found.\n",
      "\n",
      ": 41\n",
      "2019-08-15 15:00:32,224 - tensor_generators:114 - INFO - epochs: 8\n",
      "2019-08-15 15:00:32,226 - tensor_generators:115 - INFO - Generator looped & shuffled over 7392 tensors.\n",
      "2019-08-15 15:00:32,227 - tensor_generators:116 - INFO - True epoch number:8 in which 4999 tensors were presented.\n",
      "5/5 [==============================] - 20s 4s/step - loss: 0.9928 - output_bike_max_pred_hr_continuous_loss: 0.3902 - output_bike_max_hr_continuous_loss: 0.2460 - output_bike_resting_hr_continuous_loss: 0.3566 - output_bike_max_pred_hr_continuous_logcosh: 0.3902 - output_bike_max_hr_continuous_logcosh: 0.2460 - output_bike_resting_hr_continuous_logcosh: 0.3566 - val_loss: 0.9714 - val_output_bike_max_pred_hr_continuous_loss: 0.3888 - val_output_bike_max_hr_continuous_loss: 0.2315 - val_output_bike_resting_hr_continuous_loss: 0.3511 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3888 - val_output_bike_max_hr_continuous_logcosh: 0.2315 - val_output_bike_resting_hr_continuous_logcosh: 0.3511\n",
      "\n",
      "Epoch 00016: val_loss did not improve from 0.93558\n",
      "Epoch 17/20\n",
      "4/5 [=======================>......] - ETA: 1s - loss: 0.9751 - output_bike_max_pred_hr_continuous_loss: 0.3722 - output_bike_max_hr_continuous_loss: 0.2423 - output_bike_resting_hr_continuous_loss: 0.3606 - output_bike_max_pred_hr_continuous_logcosh: 0.3722 - output_bike_max_hr_continuous_logcosh: 0.2423 - output_bike_resting_hr_continuous_logcosh: 0.36062019-08-15 15:01:10,937 - tensor_generators:114 - INFO - batch_index: 63\n",
      "2019-08-15 15:01:10,939 - tensor_generators:114 - INFO - Tensors presented: 44991\n",
      "2019-08-15 15:01:10,939 - tensor_generators:114 - INFO - KeyError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 80, in multimodal_multitask_generator\n",
      "    in_batch[tm.input_name()][stats['batch_index']] = tm.tensor_from_file(hd5, dependents)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 625, in tensor_from_file\n",
      "    tensor[:, idx] = hd5[self.group][channel]\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py\", line 262, in __getitem__\n",
      "    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/h5o.pyx\", line 190, in h5py.h5o.open\n",
      "KeyError: \"Unable to open object (object 'ecg_bike_recovery' doesn't exist)\"\n",
      "\n",
      ": 21493\n",
      "2019-08-15 15:01:10,940 - tensor_generators:114 - INFO - ValueError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 86, in multimodal_multitask_generator\n",
      "    out_batch[tm.output_name()][stats['batch_index']] = tm.tensor_from_file(hd5)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 564, in tensor_from_file\n",
      "    raise ValueError(self.name + ' is a continuous value that cannot be set to 0, but no value was found.')\n",
      "ValueError: bike_resting_hr is a continuous value that cannot be set to 0, but no value was found.\n",
      "\n",
      ": 46\n",
      "2019-08-15 15:01:10,942 - tensor_generators:114 - INFO - epochs: 9\n",
      "2019-08-15 15:01:10,943 - tensor_generators:115 - INFO - Generator looped & shuffled over 7392 tensors.\n",
      "2019-08-15 15:01:10,944 - tensor_generators:116 - INFO - True epoch number:9 in which 4999 tensors were presented.\n",
      "5/5 [==============================] - 20s 4s/step - loss: 0.9976 - output_bike_max_pred_hr_continuous_loss: 0.3912 - output_bike_max_hr_continuous_loss: 0.2396 - output_bike_resting_hr_continuous_loss: 0.3668 - output_bike_max_pred_hr_continuous_logcosh: 0.3912 - output_bike_max_hr_continuous_logcosh: 0.2396 - output_bike_resting_hr_continuous_logcosh: 0.3668 - val_loss: 0.9476 - val_output_bike_max_pred_hr_continuous_loss: 0.3972 - val_output_bike_max_hr_continuous_loss: 0.2278 - val_output_bike_resting_hr_continuous_loss: 0.3226 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3972 - val_output_bike_max_hr_continuous_logcosh: 0.2278 - val_output_bike_resting_hr_continuous_logcosh: 0.3226\n",
      "\n",
      "Epoch 00017: val_loss did not improve from 0.93558\n",
      "Epoch 18/20\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "5/5 [==============================] - 21s 4s/step - loss: 0.9365 - output_bike_max_pred_hr_continuous_loss: 0.3807 - output_bike_max_hr_continuous_loss: 0.2051 - output_bike_resting_hr_continuous_loss: 0.3507 - output_bike_max_pred_hr_continuous_logcosh: 0.3807 - output_bike_max_hr_continuous_logcosh: 0.2051 - output_bike_resting_hr_continuous_logcosh: 0.3507 - val_loss: 0.9663 - val_output_bike_max_pred_hr_continuous_loss: 0.3873 - val_output_bike_max_hr_continuous_loss: 0.2360 - val_output_bike_resting_hr_continuous_loss: 0.3430 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3873 - val_output_bike_max_hr_continuous_logcosh: 0.2360 - val_output_bike_resting_hr_continuous_logcosh: 0.3430\n",
      "\n",
      "Epoch 00018: val_loss did not improve from 0.93558\n",
      "Epoch 19/20\n",
      "4/5 [=======================>......] - ETA: 1s - loss: 0.9791 - output_bike_max_pred_hr_continuous_loss: 0.4422 - output_bike_max_hr_continuous_loss: 0.2189 - output_bike_resting_hr_continuous_loss: 0.3180 - output_bike_max_pred_hr_continuous_logcosh: 0.4422 - output_bike_max_hr_continuous_logcosh: 0.2189 - output_bike_resting_hr_continuous_logcosh: 0.31802019-08-15 15:01:55,483 - tensor_generators:114 - INFO - batch_index: 6\n",
      "2019-08-15 15:01:55,484 - tensor_generators:114 - INFO - Tensors presented: 49990\n",
      "2019-08-15 15:01:55,485 - tensor_generators:114 - INFO - KeyError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 80, in multimodal_multitask_generator\n",
      "    in_batch[tm.input_name()][stats['batch_index']] = tm.tensor_from_file(hd5, dependents)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 625, in tensor_from_file\n",
      "    tensor[:, idx] = hd5[self.group][channel]\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py\", line 262, in __getitem__\n",
      "    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)\n",
      "  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n",
      "  File \"h5py/h5o.pyx\", line 190, in h5py.h5o.open\n",
      "KeyError: \"Unable to open object (object 'ecg_bike_recovery' doesn't exist)\"\n",
      "\n",
      ": 23881\n",
      "2019-08-15 15:01:55,487 - tensor_generators:114 - INFO - ValueError while attempting to generate tensor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/tensor_generators.py\", line 86, in multimodal_multitask_generator\n",
      "    out_batch[tm.output_name()][stats['batch_index']] = tm.tensor_from_file(hd5)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/ml4cvd/TensorMap.py\", line 564, in tensor_from_file\n",
      "    raise ValueError(self.name + ' is a continuous value that cannot be set to 0, but no value was found.')\n",
      "ValueError: bike_resting_hr is a continuous value that cannot be set to 0, but no value was found.\n",
      "\n",
      ": 51\n",
      "2019-08-15 15:01:55,488 - tensor_generators:114 - INFO - epochs: 10\n",
      "2019-08-15 15:01:55,489 - tensor_generators:115 - INFO - Generator looped & shuffled over 7392 tensors.\n",
      "2019-08-15 15:01:55,490 - tensor_generators:116 - INFO - True epoch number:10 in which 4999 tensors were presented.\n",
      "5/5 [==============================] - 24s 5s/step - loss: 0.9849 - output_bike_max_pred_hr_continuous_loss: 0.4369 - output_bike_max_hr_continuous_loss: 0.2273 - output_bike_resting_hr_continuous_loss: 0.3206 - output_bike_max_pred_hr_continuous_logcosh: 0.4369 - output_bike_max_hr_continuous_logcosh: 0.2273 - output_bike_resting_hr_continuous_logcosh: 0.3206 - val_loss: 0.9678 - val_output_bike_max_pred_hr_continuous_loss: 0.3878 - val_output_bike_max_hr_continuous_loss: 0.2439 - val_output_bike_resting_hr_continuous_loss: 0.3361 - val_output_bike_max_pred_hr_continuous_logcosh: 0.3878 - val_output_bike_max_hr_continuous_logcosh: 0.2439 - val_output_bike_resting_hr_continuous_logcosh: 0.3361\n",
      "\n",
      "Epoch 00019: val_loss did not improve from 0.93558\n",
      "Epoch 20/20\n",
      "5/5 [==============================] - 22s 4s/step - loss: 1.0818 - output_bike_max_pred_hr_continuous_loss: 0.4480 - output_bike_max_hr_continuous_loss: 0.2588 - output_bike_resting_hr_continuous_loss: 0.3750 - output_bike_max_pred_hr_continuous_logcosh: 0.4480 - output_bike_max_hr_continuous_logcosh: 0.2588 - output_bike_resting_hr_continuous_logcosh: 0.3750 - val_loss: 0.9804 - val_output_bike_max_pred_hr_continuous_loss: 0.4017 - val_output_bike_max_hr_continuous_loss: 0.2407 - val_output_bike_resting_hr_continuous_loss: 0.3380 - val_output_bike_max_pred_hr_continuous_logcosh: 0.4017 - val_output_bike_max_hr_continuous_logcosh: 0.2407 - val_output_bike_resting_hr_continuous_logcosh: 0.3380\n",
      "\n",
      "Epoch 00020: val_loss did not improve from 0.93558\n",
      "\n",
      "Epoch 00020: ReduceLROnPlateau reducing learning rate to 0.004999999888241291.\n",
      "2019-08-15 15:02:23,972 - plots:139 - INFO - Saved learning curves at:/home/ndiamant/ml/notebooks/recipes_output/ecg_sketch/ecg_bike_recovery_labeler/metric_history_ecg_bike_recovery_labeler.png\n",
      "2019-08-15 15:02:23,973 - models:504 - INFO - Model weights saved at: /home/ndiamant/ml/notebooks/recipes_output/ecg_sketch/ecg_bike_recovery_labeler/ecg_bike_recovery_labeler.hd5\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<Figure size 1296x1296 with 0 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "model = train_model_from_generators(model, generate_train, generate_valid, args.training_steps,\n",
    "                                        args.validation_steps, args.batch_size, args.epochs, args.patience,\n",
    "                                        args.output_folder, args.id, args.inspect_model, args.inspect_show_labels)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "step = generate_test.__next__()\n",
    "step[1].keys()\n",
    "print(step[1]['output_bike_max_pred_hr_continuous'], step[1]['output_bike_resting_hr_continuous'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "ecg_in = step[0]['input_full_ecg_bike_recovery']\n",
    "hrr_out = step[1]['output_bike_max_hr_continuous']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "pred = model.predict(ecg_in)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.scatter(hrr_out, pred[0])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "recoveries = []\n",
    "for i in range(10):\n",
    "    step = generate_test.__next__()\n",
    "    recoveries.append(step[1]['output_heart_rate_recovery_ecg_bike_autonomic_function'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
